import type { Metadata } from "next";
import "../04_styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
    >
      <body>
        {children}
      </body>
    </html>
  );
}
