import type {Metadata} from "next";
import "../04_styles/globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="de"
        >
        <body>
        <section className="container mx-auto max-w-full md:max-w-2/3 pt-8 px-8 md:px-0">
            {children}
        </section>
        </body>
        </html>
    );
}
